# Strict analyzer configuration for SmartDolap
# This file configures the analyzer with strict rules for code quality

include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
    - "**/*.mocks.dart"
    - "build/**"
    - ".dart_tool/**"

  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Treat invalid assignment as errors
    invalid_assignment: error
    # Treat undefined class as errors
    undefined_class: error
    # Treat undefined method as errors
    undefined_method: error
    # Treat undefined operator as errors
    undefined_operator: error
    # Treat undefined getter as errors
    undefined_getter: error
    # Treat undefined setter as errors
    undefined_setter: error
    # Treat undefined named parameter as errors
    undefined_named_parameter: error
    # Treat deprecated member usage as warnings
    deprecated_member_use: warning
    # Treat deprecated member usage from same package as errors
    deprecated_member_use_from_same_package: error
    lines_longer_than_80_chars: ignore

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Error rules
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    # - comment_references  # Too strict
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - no_logic_in_create_state
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    # - sort_constructors_first  # Too strict, not critical
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    # - unawaited_futures  # Will be handled case by case
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    # - unnecessary_lambdas  # Sometimes more readable
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    # - use_build_context_synchronously  # Will be handled with proper checks
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable
    - valid_regexps

    # Style rules
    - always_declare_return_types
    # - always_put_control_body_on_new_line  # Too strict for single line statements
    # - always_put_required_named_parameters_first  # Not critical
    - always_require_non_null_named_parameters
    # - always_specify_types  # Too verbose, type inference is good
    - always_use_package_imports
    - avoid_annotating_with_dynamic
    - avoid_bool_literals_in_conditional_expressions
    # - avoid_catches_without_on_clauses  # Sometimes we need to catch all
    - avoid_catching_errors
    - avoid_double_and_int_checks
    # - avoid_dynamic_calls  # Sometimes necessary with JSON
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_positional_boolean_parameters
    - avoid_print
    - avoid_private_typedef_functions
    # - avoid_redundant_argument_values  # Sometimes explicit is better
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_type_to_string
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    # - avoid_void_async  # Sometimes we need void async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    # - directives_ordering  # Auto-formatted, not critical
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - join_return_with_assignment
    - library_names
    - library_prefixes
    # - lines_longer_than_80_chars  # Already ignored above
    - no_default_cases
    - non_constant_identifier_names
    - null_closures
    - one_member_abstracts
    - only_throw_errors
    - overridden_fields
    # - package_api_docs  # Too strict
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_with_message
    - prefer_conditional_assignment
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    # - prefer_expression_function_bodies  # Not always more readable
    - prefer_generic_function_type_aliases
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_void_to_null
    # - public_member_api_docs  # Too strict
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - type_annotate_public_apis
    - type_init_formals
